### Create a freelancer
POST http://localhost:8080/freelancer
Content-Type: application/json

{
  "firstName": "first",
  "secondName": "second",
  "nickName": "nick",
  "email": "a@a.a"
}

### Get an existing freelancer
GET http://localhost:8080/freelancer/1

### Get an non-existing freelancer
GET http://localhost:8080/freelancer/100500

### Create a project
POST http://localhost:8080/project
Content-Type: application/json

{
  "name": "proj",
  "clientId": 1,
  "freelancerIds": [1]
}