apiVersion: v1
kind: Service
metadata:
  name: platform-service
spec:
  type: NodePort
  selector:
    app: platform-app
  ports:
  - nodePort: 32222
    port: 8080
    targetPort: platform-port
    protocol: TCP
