apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: NodePort
  selector:
    app: postgres-app
  ports:
  - nodePort: 31111
    port: 5432
    targetPort: postgres-port
    protocol: TCP
