### Create a freelancer
POST http://localhost:{{port}}/freelancer
Content-Type: application/json

{
  "firstName": "first",
  "secondName": "second",
  "nickName": "nick",
  "email": "a@a.a"
}

### Get an existing freelancer
GET http://localhost:{{port}}/freelancer/1

### Get an non-existing freelancer
GET http://localhost:{{port}}/freelancer/100500

### Create a client
POST http://localhost:{{port}}/client
Content-Type: application/json

{
  "firstName": "first",
  "secondName": "second",
  "email": "a@a.a"
}

### Get an existing client
GET http://localhost:{{port}}/client/1

### Get an non-existing freelancer
GET http://localhost:{{port}}/client/100500

### Create a project
POST http://localhost:{{port}}/project
Content-Type: application/json

{
  "name": "proj",
  "clientId": 1,
  "freelancerIds": [1]
}

### Get an existing project
GET http://localhost:{{port}}/project/1